# Generated by Django 5.2.4 on 2025-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
